#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: k3d-registry:5000/traefik-forward-auth:latest
        imagePullPolicy: Always
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: INSECURE_COOKIE
          value: "true"
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          value: 72515094321-f46g0uilgl4fkqf2fpk1sjfg06umtb27.apps.googleusercontent.com
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          value: 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
        - name: PROVIDERS_GOOGLE_SCOPE
          value: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/bigquery
        - name: SECRET
          value: something
        - name: URL_PATH
          value: /auth/_oauth

---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181

---
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://traefik-forward-auth.default.svc.cluster.local:4181
    authResponseHeadersRegex: ^X-

# ---
# #
# # IngressRoute
# #
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: traefik-forward-auth
#   labels:
#     app: traefik-forward-auth
# spec:
#   entryPoints:
#     - web
#   routes:
#   - match: "PathPrefix(`/auth/`)"
#     kind: Rule
#     services:
#       - name: traefik-forward-auth
#         port: 4181